name: Build and Deploy to Azure Functions

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: DurableFunction
        slot-name: production
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        package: .\bin\Release\netcoreapp3.1\publish
